# Generated by Django 5.2 on 2025-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfertaLogua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oferta", models.CharField(max_length=200)),
                ("seccion", models.CharField(max_length=30)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "imagen_1",
                    models.ImageField(blank=True, null=True, upload_to="ofertas"),
                ),
                (
                    "imagen_2",
                    models.ImageField(blank=True, null=True, upload_to="ofertas/"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("stock", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
